language: go
go:
  - "1.13"
  - "master"
matrix:
  allow_failures:
    - go: "master"
script:
  - go test -v -race -bench . -benchmem ./...
  - go test -v -tags binary_log -race -bench . -benchmem ./...