language: go
go:
  - "1.13"
  - "master"
matrix:
  allow_failures:
    - go: "master"
script:
  - go test -v -race -cpu=1 -bench . -benchmem ./...
  - go test -v -tags binary_log -race -cpu=1 -bench . -benchmem ./...